update

diff --git a/charts/v4.0/cray-nls/values.yaml b/charts/v4.0/cray-nls/values.yaml
--- a/charts/v4.0/cray-nls/values.yaml
+++ b/charts/v4.0/cray-nls/values.yaml
@@ -217,6 +217,37 @@ argo-workflows:
       # -- Registry to use for the controller
       repository: quay.io/argoproj/argoexec
       tag: v3.3.6
+  initContainers:
+    wait-for-postgresql:
+      name: "wait-for-postgresql"
+      image: "{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}"
+      imagePullPolicy: "{{ .Values.kubectl.image.pullPolicy }}"
+      command:
+        - /bin/sh
+        - -c
+        - |
+          while true; do
+            JOB_CONDITION="$(kubectl get jobs -n {{ .Release.Namespace }} -l app.kubernetes.io/name={{ cray-postgresql.nameOverride }}-wait-for-postgres -o jsonpath='{.items[0].status.conditions[0].type}')"
+            JOB_CONDITION_RC=$?
+            if [ $JOB_CONDITION_RC -eq 0 ]; then
+              if [ "$JOB_CONDITION" == 'Complete' ]; then
+                echo "Completed"
+                break
+              fi
+              echo "Waiting for the {{ index .Values "cray-etcd-base" "nameOverride" }}-wait-for-etcd job in the {{ .Release.Namespace }} namespace to complete, current condition is $(kubectl get jobs -n {{ .Release.Namespace }} -l app.kubernetes.io/name={{ .Values.cray-postgresql.nameOverride }}-wait-for-postgres -o jsonpath='{.items[0].status}')"
+              sleep 3
+            elif [ $JOB_CONDITION_RC -ne 1 ]; then
+              echo "'kubectl get jobs' failed with exit code $JOB_CONDITION_RC , failing"
+              exit 1
+            else
+              echo "'kubectl get jobs' failed with exit code $JOB_CONDITION_RC , will retry"
+              sleep 3
+            fi
+          done
+      securityContext:
+        runAsUser: 65534
+        runAsGroup: 65534
+        runAsNonRoot: true
   server:
     affinity:
       podAntiAffinity:
@@ -235,37 +266,6 @@ argo-workflows:
       # -- Registry to use for the controller
       repository: quay.io/argoproj/argocli
       tag: v3.4.5
-    initContainers:
-      wait-for-postgresql:
-        name: "wait-for-postgresql"
-        image: "{{ .Values.kubectl.image.repository }}:{{ .Values.kubectl.image.tag }}"
-        imagePullPolicy: "{{ .Values.kubectl.image.pullPolicy }}"
-        command:
-          - /bin/sh
-          - -c
-          - |
-            while true; do
-              JOB_CONDITION="$(kubectl get jobs -n {{ .Release.Namespace }} -l app.kubernetes.io/name={{ cray-postgresql.nameOverride }}-wait-for-postgres -o jsonpath='{.items[0].status.conditions[0].type}')"
-              JOB_CONDITION_RC=$?
-              if [ $JOB_CONDITION_RC -eq 0 ]; then
-                if [ "$JOB_CONDITION" == 'Complete' ]; then
-                  echo "Completed"
-                  break
-                fi
-                echo "Waiting for the {{ index .Values "cray-etcd-base" "nameOverride" }}-wait-for-etcd job in the {{ .Release.Namespace }} namespace to complete, current condition is $(kubectl get jobs -n {{ .Release.Namespace }} -l app.kubernetes.io/name={{ .Values.cray-postgresql.nameOverride }}-wait-for-postgres -o jsonpath='{.items[0].status}')"
-                sleep 3
-              elif [ $JOB_CONDITION_RC -ne 1 ]; then
-                echo "'kubectl get jobs' failed with exit code $JOB_CONDITION_RC , failing"
-                exit 1
-              else
-                echo "'kubectl get jobs' failed with exit code $JOB_CONDITION_RC , will retry"
-                sleep 3
-              fi
-            done
-        securityContext:
-          runAsUser: 65534
-          runAsGroup: 65534
-          runAsNonRoot: true
     pdb:
       enabled: true
       minAvailable: 1
